import streamlit as st
import pandas as pd
import io
import uuid
from datetime import datetime, timedelta, date
from utils.data_persistence import load_json, save_json
from utils.ui_helpers import render_module_header
from utils.chart_config import apply_layout, CHART_COLORS
from utils.formatting import format_currency, format_currency_int, get_currency_symbol

DATA_FILE = "freelance_data.json"
OLD_DATA_FILE = "job_applications.json"
STATUSES = ["In Progress", "Completed", "Invoiced", "Paid", "On Hold", "Cancelled"]


def _load():
    import os
    from utils.data_persistence import _path
    # Migrate old data file name if needed
    old_path = _path(OLD_DATA_FILE)
    new_path = _path(DATA_FILE)
    if os.path.exists(old_path) and not os.path.exists(new_path):
        import shutil
        shutil.copy2(old_path, new_path)
    return load_json(DATA_FILE, default={"clients": [], "invoices": []})


def _save(data):
    save_json(DATA_FILE, data)


def _migrate_old_format(data):
    """Migrate from old job application list format to new freelance format."""
    if isinstance(data, list):
        # Old format: list of job applications — migrate to new structure
        return {"clients": [], "invoices": []}
    if "clients" not in data:
        data["clients"] = []
    if "invoices" not in data:
        data["invoices"] = []
    return data


def _generate_invoice_pdf(invoice, client_name, user_name):
    """Generate a clean invoice PDF and return bytes."""
    from fpdf import FPDF
    sym = get_currency_symbol()

    pdf = FPDF()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 15, "INVOICE", align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Invoice #{invoice['id'].upper()}", align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Date: {invoice['date']}", align="R", new_x="LMARGIN", new_y="NEXT")
    status_text = "PAID" if invoice.get("paid") else "UNPAID"
    pdf.cell(0, 6, f"Status: {status_text}", align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # From
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(50, 50, 80)
    pdf.cell(95, 7, "From:", new_x="RIGHT")
    pdf.cell(95, 7, "Bill To:", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(95, 6, user_name or "Your Name", new_x="RIGHT")
    pdf.cell(95, 6, client_name, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(12)

    # Line items table header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(99, 102, 241)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(80, 8, "Description", border=1, fill=True, align="C")
    pdf.cell(30, 8, "Qty / Hours", border=1, fill=True, align="C")
    pdf.cell(35, 8, "Rate", border=1, fill=True, align="C")
    pdf.cell(35, 8, "Amount", border=1, fill=True, align="C")
    pdf.ln()

    # Line items
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    for item in invoice.get("line_items", []):
        desc = str(item.get("description", ""))[:40]
        qty = item.get("quantity", 0)
        rate = item.get("rate", 0)
        amount = qty * rate
        pdf.cell(80, 7, desc, border=1)
        pdf.cell(30, 7, f"{qty:.1f}", border=1, align="C")
        pdf.cell(35, 7, f"{sym}{rate:,.2f}", border=1, align="R")
        pdf.cell(35, 7, f"{sym}{amount:,.2f}", border=1, align="R")
        pdf.ln()

    # Total
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(50, 50, 80)
    pdf.cell(145, 10, "Total:", align="R")
    pdf.cell(35, 10, f"{sym}{invoice['amount']:,.2f}", align="R")
    pdf.ln(20)

    # Payment terms
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(80, 80, 80)
    terms = invoice.get("payment_terms", "Net 30")
    pdf.cell(0, 7, f"Payment Terms: {terms}", new_x="LMARGIN", new_y="NEXT")

    # Notes
    if invoice.get("notes"):
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"Notes: {invoice['notes']}", new_x="LMARGIN", new_y="NEXT")

    # Thank you footer
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 8, "Thank you for your business!", align="C", new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.set_y(-30)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, "Generated by FinanceKit", align="C")

    return bytes(pdf.output())


def render():
    render_module_header("💼", "Freelance Dashboard",
                         "Track clients, log work, generate invoices, and monitor your freelance income.")

    if "freelance_data" not in st.session_state:
        raw = _load()
        st.session_state.freelance_data = _migrate_old_format(raw)

    data = st.session_state.freelance_data
    clients = data.get("clients", [])
    invoices = data.get("invoices", [])

    tab_overview, tab_clients, tab_invoices, tab_income = st.tabs([
        "📊 Overview", "👥 Clients & Jobs", "📄 Invoices", "💵 Income"
    ])

    # ── Overview Tab ─────────────────────────────────────────────────────
    with tab_overview:
        total_invoiced = sum(inv["amount"] for inv in invoices)
        total_paid = sum(inv["amount"] for inv in invoices if inv.get("paid"))
        total_outstanding = total_invoiced - total_paid
        active_clients = len([c for c in clients if c.get("status") in ("In Progress", "Completed", "Invoiced")])

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Total Invoiced", format_currency(total_invoiced))
        m2.metric("Total Paid", format_currency(total_paid))
        m3.metric("Outstanding", format_currency(total_outstanding),
                   delta=f"-{format_currency(total_outstanding)}" if total_outstanding > 0 else None,
                   delta_color="inverse")
        m4.metric("Active Clients", active_clients)

        if total_outstanding > 0:
            unpaid = [inv for inv in invoices if not inv.get("paid")]
            if unpaid:
                st.warning(f"💸 You have **{len(unpaid)}** unpaid invoice(s) totaling **{format_currency(total_outstanding)}**.")

        # Monthly income chart
        if invoices:
            st.markdown("---")
            st.markdown("### Monthly Freelance Income")
            paid_invoices = [inv for inv in invoices if inv.get("paid")]
            if paid_invoices:
                import plotly.express as px
                inv_df = pd.DataFrame(paid_invoices)
                inv_df["date"] = pd.to_datetime(inv_df["date"], errors="coerce")
                inv_df = inv_df.dropna(subset=["date"])
                if not inv_df.empty:
                    inv_df["month"] = inv_df["date"].dt.to_period("M").astype(str)
                    monthly = inv_df.groupby("month")["amount"].sum().reset_index()
                    monthly.columns = ["Month", "Income ($)"]
                    fig = px.bar(
                        monthly, x="Month", y="Income ($)",
                        color_discrete_sequence=["#22c55e"],
                        text="Income ($)",
                    )
                    fig.update_traces(texttemplate=f"{get_currency_symbol()}%{{text:,.0f}}", textposition="outside")
                    apply_layout(fig, height=300, margin=dict(t=20, b=10))
                    st.plotly_chart(fig, use_container_width=True)
            else:
                st.info("Mark invoices as paid to see your income chart.")

        # Client profitability
        if clients and invoices:
            st.markdown("---")
            st.markdown("### Client Profitability")
            client_totals = {}
            for inv in invoices:
                if inv.get("paid"):
                    cname = inv.get("client", "Unknown")
                    client_totals[cname] = client_totals.get(cname, 0) + inv["amount"]

            if client_totals:
                import plotly.express as px
                prof_df = pd.DataFrame(
                    sorted(client_totals.items(), key=lambda x: x[1], reverse=True),
                    columns=["Client", "Total Paid ($)"]
                )
                fig = px.bar(
                    prof_df, x="Total Paid ($)", y="Client",
                    orientation="h",
                    color_discrete_sequence=["#6366f1"],
                    text="Total Paid ($)",
                )
                fig.update_traces(texttemplate=f"{get_currency_symbol()}%{{text:,.0f}}", textposition="outside")
                fig.update_layout(
                    height=max(200, len(client_totals) * 45),
                    margin=dict(t=10, b=10, l=10, r=60),
                    plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                    font=dict(color="#e2e8f0"),
                    xaxis=dict(gridcolor="#2a2a40"),
                    yaxis=dict(gridcolor="#2a2a40"),
                    showlegend=False,
                )
                st.plotly_chart(fig, use_container_width=True)

    # ── Clients & Jobs Tab ───────────────────────────────────────────────
    with tab_clients:
        with st.expander("➕ Add New Client / Job", expanded=not clients):
            with st.form("add_client", clear_on_submit=True):
                fc1, fc2 = st.columns(2)
                with fc1:
                    client_name = st.text_input("Client / Company Name *")
                    project = st.text_input("Project / Job Description *")
                    date_started = st.date_input("Date Started", value=date.today())
                with fc2:
                    status = st.selectbox("Status", STATUSES)
                    rate_type = st.selectbox("Rate Type", ["Hourly", "Flat Rate"])
                    rate = st.number_input("Rate ($)", min_value=0.0, step=10.0, format="%.2f")
                notes = st.text_area("Notes", height=60)

                if st.form_submit_button("➕ Add Client/Job", type="primary", use_container_width=True):
                    if not client_name or not project:
                        st.error("Client name and project are required.")
                    else:
                        clients.append({
                            "id": str(uuid.uuid4())[:8],
                            "client": client_name,
                            "project": project,
                            "date_started": str(date_started),
                            "status": status,
                            "rate_type": rate_type,
                            "rate": rate,
                            "notes": notes,
                        })
                        data["clients"] = clients
                        _save(data)
                        st.toast(f"Added {client_name}!", icon="✅")
                        st.rerun()

        if not clients:
            st.info("No clients yet — add your first one above.")
        else:
            # Status filter
            filter_status = st.multiselect("Filter by status", STATUSES, default=STATUSES, key="client_filter")
            filtered = [c for c in clients if c.get("status") in filter_status]

            # Pipeline chart
            if filtered:
                import plotly.express as px
                status_counts = {}
                for c in clients:
                    s = c.get("status", "In Progress")
                    status_counts[s] = status_counts.get(s, 0) + 1
                pipe_df = pd.DataFrame({"Status": list(status_counts.keys()), "Count": list(status_counts.values())})
                colors = ["#6366f1", "#22c55e", "#f59e0b", "#34d399", "#94a3b8", "#ef4444"]
                fig = px.bar(pipe_df, x="Status", y="Count", color="Status",
                             color_discrete_sequence=colors, text="Count")
                fig.update_layout(showlegend=False, height=220, margin=dict(t=10, b=10),
                                  plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                                  font=dict(color="#e2e8f0"))
                fig.update_traces(textposition="outside")
                st.plotly_chart(fig, use_container_width=True)

            for c in filtered:
                status_icons = {
                    "In Progress": "🔵", "Completed": "🟢", "Invoiced": "🟡",
                    "Paid": "✅", "On Hold": "⏸️", "Cancelled": "🔴",
                }
                icon = status_icons.get(c.get("status"), "⚪")
                rate_str = f"{format_currency(c['rate'])}/{('hr' if c.get('rate_type') == 'Hourly' else 'flat')}" if c.get("rate") else ""
                label = f"{icon} **{c['client']}** — {c['project']} ({c.get('status')}) {rate_str}"

                with st.expander(label):
                    dc1, dc2 = st.columns(2)
                    with dc1:
                        st.write(f"**Started:** {c.get('date_started', 'N/A')}")
                        st.write(f"**Rate:** {rate_str or 'Not set'}")
                    with dc2:
                        if c.get("notes"):
                            st.write(f"**Notes:** {c['notes']}")

                    ec1, ec2, ec3 = st.columns([2, 2, 1])
                    with ec1:
                        new_status = st.selectbox(
                            "Status", STATUSES,
                            index=STATUSES.index(c["status"]) if c["status"] in STATUSES else 0,
                            key=f"cs_{c['id']}",
                        )
                    with ec2:
                        new_notes = st.text_input("Notes", value=c.get("notes", ""), key=f"cn_{c['id']}")
                    with ec3:
                        st.markdown("<br>", unsafe_allow_html=True)
                        if st.button("💾 Save", key=f"csave_{c['id']}"):
                            for item in data["clients"]:
                                if item["id"] == c["id"]:
                                    item["status"] = new_status
                                    item["notes"] = new_notes
                                    break
                            _save(data)
                            st.toast("Updated!", icon="✅")
                            st.rerun()

                    if st.button("🗑️ Delete", key=f"cdel_{c['id']}"):
                        data["clients"] = [x for x in data["clients"] if x["id"] != c["id"]]
                        _save(data)
                        st.rerun()

    # ── Invoices Tab ─────────────────────────────────────────────────────
    with tab_invoices:
        st.markdown("### Generate Invoice")

        client_names = list({c["client"] for c in clients}) if clients else []

        if not client_names:
            st.info("Add a client first in the Clients & Jobs tab.")
        else:
            with st.form("create_invoice", clear_on_submit=True):
                ic1, ic2 = st.columns(2)
                with ic1:
                    inv_client = st.selectbox("Client", client_names)
                    inv_date = st.date_input("Invoice Date", value=date.today())
                    user_name = st.text_input("Your Name (for invoice header)", "")
                with ic2:
                    payment_terms = st.selectbox("Payment Terms", ["Net 30", "Net 15", "Net 60", "Due on Receipt"])
                    inv_notes = st.text_input("Notes (optional)")

                st.markdown("**Line Items**")
                st.caption("Add up to 5 line items. Leave description blank to skip.")

                line_items = []
                for li in range(5):
                    lc1, lc2, lc3 = st.columns([3, 1, 1])
                    with lc1:
                        desc = st.text_input(f"Description", key=f"li_desc_{li}",
                                             placeholder="Web development" if li == 0 else "")
                    with lc2:
                        qty = st.number_input(f"Qty/Hours", min_value=0.0, step=1.0, key=f"li_qty_{li}", format="%.1f")
                    with lc3:
                        li_rate = st.number_input(f"Rate ($)", min_value=0.0, step=10.0, key=f"li_rate_{li}", format="%.2f")

                    if desc.strip():
                        line_items.append({"description": desc, "quantity": qty, "rate": li_rate})

                if st.form_submit_button("📄 Create Invoice", type="primary", use_container_width=True):
                    if not line_items:
                        st.error("Add at least one line item.")
                    else:
                        total = sum(item["quantity"] * item["rate"] for item in line_items)
                        new_invoice = {
                            "id": str(uuid.uuid4())[:8],
                            "client": inv_client,
                            "date": str(inv_date),
                            "amount": round(total, 2),
                            "line_items": line_items,
                            "notes": inv_notes,
                            "payment_terms": payment_terms,
                            "paid": False,
                            "user_name": user_name,
                        }
                        invoices.append(new_invoice)
                        data["invoices"] = invoices
                        _save(data)
                        st.toast(f"Invoice created: {format_currency(total)} for {inv_client}", icon="📄")
                        st.rerun()

        # Invoice list
        if invoices:
            st.markdown("---")
            st.markdown("### All Invoices")

            # Summary
            unpaid = [inv for inv in invoices if not inv.get("paid")]
            paid = [inv for inv in invoices if inv.get("paid")]
            ic1, ic2 = st.columns(2)
            ic1.metric("Unpaid Invoices", f"{len(unpaid)} ({format_currency(sum(i['amount'] for i in unpaid))})")
            ic2.metric("Paid Invoices", f"{len(paid)} ({format_currency(sum(i['amount'] for i in paid))})")

            for inv in sorted(invoices, key=lambda x: x["date"], reverse=True):
                paid_icon = "✅" if inv.get("paid") else "⏳"
                label = f"{paid_icon} #{inv['id'].upper()} — {inv['client']} — {format_currency(inv['amount'])} ({inv['date']})"

                with st.expander(label):
                    # Line items table
                    if inv.get("line_items"):
                        li_data = []
                        for item in inv["line_items"]:
                            li_data.append({
                                "Description": item["description"],
                                "Qty/Hours": item["quantity"],
                                "Rate": format_currency(item['rate']),
                                "Amount": format_currency(item['quantity'] * item['rate']),
                            })
                        st.dataframe(pd.DataFrame(li_data), use_container_width=True, hide_index=True)

                    st.markdown(f"**Total: {format_currency(inv['amount'])}**")
                    if inv.get("notes"):
                        st.caption(f"Notes: {inv['notes']}")

                    bc1, bc2, bc3 = st.columns(3)
                    with bc1:
                        if inv.get("paid"):
                            if st.button("↩️ Mark Unpaid", key=f"unpay_{inv['id']}"):
                                for item in data["invoices"]:
                                    if item["id"] == inv["id"]:
                                        item["paid"] = False
                                        break
                                _save(data)
                                st.rerun()
                        else:
                            if st.button("✅ Mark Paid", key=f"pay_{inv['id']}", type="primary"):
                                for item in data["invoices"]:
                                    if item["id"] == inv["id"]:
                                        item["paid"] = True
                                        break
                                _save(data)
                                st.toast("Invoice marked as paid!", icon="✅")
                                st.rerun()
                    with bc2:
                        try:
                            pdf_bytes = _generate_invoice_pdf(
                                inv, inv["client"], inv.get("user_name", "")
                            )
                            st.download_button(
                                "⬇️ Download PDF",
                                data=pdf_bytes,
                                file_name=f"invoice_{inv['id']}.pdf",
                                mime="application/pdf",
                                key=f"pdf_{inv['id']}",
                            )
                        except Exception as e:
                            st.error(f"PDF error: {e}")
                    with bc3:
                        if st.button("🗑️ Delete", key=f"idel_{inv['id']}"):
                            data["invoices"] = [x for x in data["invoices"] if x["id"] != inv["id"]]
                            _save(data)
                            st.rerun()

    # ── Income Tab ───────────────────────────────────────────────────────
    with tab_income:
        if not invoices:
            st.info("Create invoices to see income analytics.")
        else:
            paid_invoices = [inv for inv in invoices if inv.get("paid")]
            all_total = sum(inv["amount"] for inv in invoices)
            paid_total = sum(inv["amount"] for inv in paid_invoices)

            im1, im2, im3 = st.columns(3)
            im1.metric("Lifetime Income (Paid)", format_currency(paid_total))
            im2.metric("Total Invoiced", format_currency(all_total))
            im3.metric("Collection Rate",
                        f"{paid_total / all_total * 100:.0f}%" if all_total > 0 else "N/A")

            if paid_invoices:
                import plotly.express as px
                inv_df = pd.DataFrame(paid_invoices)
                inv_df["date"] = pd.to_datetime(inv_df["date"], errors="coerce")
                inv_df = inv_df.dropna(subset=["date"])

                if not inv_df.empty:
                    inv_df["month"] = inv_df["date"].dt.to_period("M").astype(str)
                    monthly = inv_df.groupby("month")["amount"].sum().reset_index()
                    monthly.columns = ["Month", "Income ($)"]

                    st.markdown("### Monthly Income")
                    fig = px.bar(monthly, x="Month", y="Income ($)",
                                 color_discrete_sequence=["#22c55e"], text="Income ($)")
                    fig.update_traces(texttemplate=f"{get_currency_symbol()}%{{text:,.0f}}", textposition="outside")
                    fig.update_layout(
                        height=320, margin=dict(t=20, b=10),
                        plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                        font=dict(color="#e2e8f0"),
                        xaxis=dict(gridcolor="#2a2a40"), yaxis=dict(gridcolor="#2a2a40"),
                    )
                    st.plotly_chart(fig, use_container_width=True)

                    # Client breakdown
                    st.markdown("### Income by Client")
                    client_income = inv_df.groupby("client")["amount"].sum().reset_index()
                    client_income.columns = ["Client", "Total ($)"]
                    client_income = client_income.sort_values("Total ($)", ascending=False)

                    fig2 = px.pie(client_income, names="Client", values="Total ($)",
                                  color_discrete_sequence=px.colors.qualitative.Set2)
                    fig2.update_layout(
                        height=320, margin=dict(t=20, b=10),
                        paper_bgcolor="rgba(0,0,0,0)", font=dict(color="#e2e8f0"),
                    )
                    st.plotly_chart(fig2, use_container_width=True)

            # Export
            st.markdown("---")
            export_data = []
            for inv in invoices:
                export_data.append({
                    "Invoice #": inv["id"].upper(),
                    "Client": inv["client"],
                    "Date": inv["date"],
                    "Amount": inv["amount"],
                    "Status": "Paid" if inv.get("paid") else "Unpaid",
                    "Notes": inv.get("notes", ""),
                })
            csv_bytes = pd.DataFrame(export_data).to_csv(index=False).encode("utf-8")
            st.download_button(
                "⬇️ Export All Invoices (CSV)",
                data=csv_bytes,
                file_name="freelance_invoices.csv",
                mime="text/csv",
            )
