import io
import os
import tempfile
from datetime import datetime

from fpdf import FPDF
import plotly.graph_objects as go
import plotly.io as pio


def _sanitize(text: str) -> str:
    """Replace unicode characters that Helvetica can't render."""
    replacements = {
        "\u2014": "-",   # em dash
        "\u2013": "-",   # en dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2026": "...", # ellipsis
        "\u2022": "-",   # bullet
    }
    for char, repl in replacements.items():
        text = text.replace(char, repl)
    return text


class ReportPDF(FPDF):
    def __init__(self, title: str = "Financial Report", user_name: str = ""):
        super().__init__()
        self.report_title = title
        self.user_name = user_name

    def header(self):
        # Colored header bar
        self.set_fill_color(99, 102, 241)
        self.rect(0, 0, self.w, 8, "F")
        # Gradient accent (lighter indigo)
        self.set_fill_color(167, 139, 250)
        self.rect(self.w * 0.7, 0, self.w * 0.3, 8, "F")
        self.set_y(12)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(99, 102, 241)
        self.cell(0, 6, "FinanceKit", align="L")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, self.report_title, align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by FinanceKit", align="C")

    def add_title_page(self, date_range: str = ""):
        self.add_page()
        self.ln(40)
        # Decorative line
        self.set_draw_color(99, 102, 241)
        self.set_line_width(1.5)
        self.line(60, self.get_y(), self.w - 60, self.get_y())
        self.ln(10)

        self.set_font("Helvetica", "B", 32)
        self.set_text_color(50, 50, 80)
        self.cell(0, 18, _sanitize(self.report_title), align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(6)

        # Decorative line
        self.set_draw_color(167, 139, 250)
        self.set_line_width(0.5)
        self.line(70, self.get_y(), self.w - 70, self.get_y())
        self.ln(8)

        self.set_font("Helvetica", "", 13)
        self.set_text_color(100, 100, 100)
        if self.user_name:
            self.cell(0, 10, _sanitize(f"Prepared for: {self.user_name}"), align="C", new_x="LMARGIN", new_y="NEXT")
        if date_range:
            self.cell(0, 10, _sanitize(f"Period: {date_range}"), align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(
            0, 10,
            f"Generated: {datetime.now().strftime('%B %d, %Y')}",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )

    def add_section_header(self, text: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(99, 102, 241)
        self.cell(0, 12, _sanitize(text), new_x="LMARGIN", new_y="NEXT")
        # Underline
        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.l_margin + 60, self.get_y())
        self.ln(6)

    def add_stat_line(self, label: str, value: str):
        self.set_font("Helvetica", "", 11)
        self.set_text_color(80, 80, 80)
        self.cell(70, 8, _sanitize(label), new_x="RIGHT")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(50, 50, 80)
        self.cell(0, 8, _sanitize(value), new_x="LMARGIN", new_y="NEXT")

    def add_summary_box(self, stats: dict):
        """Add a bordered summary box with key stats."""
        self.ln(4)
        x_start = self.l_margin
        box_w = self.w - self.l_margin - self.r_margin
        box_h = 8 * len(stats) + 12

        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.5)
        self.rect(x_start, self.get_y(), box_w, box_h)

        self.set_fill_color(245, 243, 255)
        self.rect(x_start + 0.5, self.get_y() + 0.5, box_w - 1, box_h - 1, "F")

        self.ln(4)
        for label, value in stats.items():
            self.set_font("Helvetica", "", 10)
            self.set_text_color(80, 80, 80)
            self.cell(80, 7, f"  {_sanitize(label)}", new_x="RIGHT")
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(50, 50, 80)
            self.cell(0, 7, _sanitize(value), new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def add_chart_image(self, fig: go.Figure, width: int = 180):
        """Render a Plotly figure to a temp PNG and embed it."""
        import subprocess
        import sys
        import json as _json

        tmp_json = os.path.join(tempfile.gettempdir(), f"fk_fig_{id(fig)}.json")
        tmp_png = os.path.join(tempfile.gettempdir(), f"fk_fig_{id(fig)}.png")

        try:
            fig.update_layout(margin=dict(l=60, r=40, t=50, b=80))
            with open(tmp_json, "w") as f:
                f.write(fig.to_json())

            script = (
                "import plotly.io as pio, json, sys;"
                f"fig = pio.from_json(open(r'{tmp_json}').read());"
                f"fig.write_image(r'{tmp_png}', format='png', width=900, height=600, scale=2)"
            )
            result = subprocess.run(
                [sys.executable, "-c", script],
                capture_output=True, text=True, timeout=30,
            )
            if result.returncode != 0:
                raise RuntimeError(result.stderr[-200:])

            self.image(tmp_png, w=width)
            self.ln(6)
        except Exception as e:
            self.set_font("Helvetica", "I", 10)
            self.cell(0, 8, f"[Chart error: {_sanitize(str(e)[:80])}]",
                      new_x="LMARGIN", new_y="NEXT")
        finally:
            for p in (tmp_json, tmp_png):
                try:
                    os.unlink(p)
                except OSError:
                    pass

    def add_table(self, headers: list[str], rows: list[list[str]], col_widths: list[int] | None = None):
        if col_widths is None:
            page_w = self.w - self.l_margin - self.r_margin
            col_widths = [int(page_w / len(headers))] * len(headers)

        # Header
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(99, 102, 241)
        self.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 8, _sanitize(h), border=1, fill=True, align="C")
        self.ln()

        # Rows with alternating background
        self.set_font("Helvetica", "", 8)
        for row_idx, row in enumerate(rows):
            if self.get_y() > 265:
                self.add_page()
            if row_idx % 2 == 0:
                self.set_fill_color(248, 248, 252)
            else:
                self.set_fill_color(255, 255, 255)
            self.set_text_color(40, 40, 40)
            for i, cell_text in enumerate(row):
                self.cell(col_widths[i], 7, _sanitize(str(cell_text)[:40]), border=1, fill=True, align="C")
            self.ln()

    def get_bytes(self) -> bytes:
        self.alias_nb_pages()
        return bytes(self.output())


# ── Report Templates (v5.6) ───────────────────────────────────────────


def generate_monthly_summary(user_name: str, settings: dict, data: dict) -> bytes:
    """Generate a Monthly Summary PDF report."""
    pdf = ReportPDF("Monthly Summary", user_name)
    now = datetime.now()
    month_str = now.strftime("%B %Y")
    pdf.add_title_page(month_str)

    pdf.add_page()
    pdf.add_section_header("Income vs Expenses")

    transactions = data.get("transactions", [])
    budgets = data.get("budgets", {})
    current_month = now.strftime("%Y-%m")

    month_txns = [t for t in transactions if t.get("date", "")[:7] == current_month]
    total_spent = sum(float(t.get("amount", 0)) for t in month_txns)
    total_budget = sum(float(v) for v in budgets.values()) if budgets else 0
    savings_rate = ((total_budget - total_spent) / total_budget * 100) if total_budget > 0 else 0

    pdf.add_summary_box({
        "Total Spending": f"${total_spent:,.2f}",
        "Total Budget": f"${total_budget:,.2f}",
        "Savings Rate": f"{savings_rate:.1f}%",
        "Transactions": str(len(month_txns)),
    })

    # Spending by category
    if month_txns:
        pdf.add_section_header("Spending by Category")
        by_cat = {}
        for t in month_txns:
            cat = t.get("category", "Other")
            by_cat[cat] = by_cat.get(cat, 0) + float(t.get("amount", 0))

        headers = ["Category", "Amount", "% of Total"]
        rows = []
        for cat, amount in sorted(by_cat.items(), key=lambda x: -x[1]):
            pct = (amount / total_spent * 100) if total_spent > 0 else 0
            rows.append([cat, f"${amount:,.2f}", f"{pct:.1f}%"])
        pdf.add_table(headers, rows, [70, 50, 40])

    return pdf.get_bytes()


def generate_year_in_review(user_name: str, settings: dict, data: dict) -> bytes:
    """Generate a Year-in-Review PDF report."""
    pdf = ReportPDF("Year in Review", user_name)
    year = datetime.now().year
    pdf.add_title_page(f"January - December {year}")

    pdf.add_page()
    pdf.add_section_header("Annual Overview")

    transactions = data.get("transactions", [])
    year_str = str(year)
    year_txns = [t for t in transactions if t.get("date", "")[:4] == year_str]
    total_spent = sum(float(t.get("amount", 0)) for t in year_txns)
    avg_monthly = total_spent / 12

    goals = data.get("goals", [])
    goals_achieved = sum(1 for g in goals if g.get("current", 0) >= g.get("target", 1))

    pdf.add_summary_box({
        "Total Annual Spending": f"${total_spent:,.2f}",
        "Average Monthly": f"${avg_monthly:,.2f}",
        "Transactions": str(len(year_txns)),
        "Goals Achieved": str(goals_achieved),
    })

    return pdf.get_bytes()


def generate_tax_summary(user_name: str, settings: dict, data: dict) -> bytes:
    """Generate a Tax Summary PDF report."""
    pdf = ReportPDF("Tax Summary", user_name)
    year = datetime.now().year - 1  # Previous tax year
    pdf.add_title_page(f"Tax Year {year}")

    pdf.add_page()
    pdf.add_section_header("Tax-Deductible Expenses")

    transactions = data.get("transactions", [])
    year_str = str(year)
    year_txns = [t for t in transactions if t.get("date", "")[:4] == year_str]

    # Get tax-deductible categories from settings
    tax_cats = settings.get("tax_categories", [])
    if not tax_cats:
        tax_cats = ["Health", "Utilities", "Housing"]

    tax_txns = [t for t in year_txns if t.get("category", "") in tax_cats]
    total_deductible = sum(float(t.get("amount", 0)) for t in tax_txns)

    pdf.add_summary_box({
        "Total Deductible": f"${total_deductible:,.2f}",
        "Deductible Transactions": str(len(tax_txns)),
        "Categories": ", ".join(tax_cats[:5]),
    })

    # Quarterly breakdown
    pdf.add_section_header("Quarterly Breakdown")
    quarters = {"Q1": ("01", "03"), "Q2": ("04", "06"), "Q3": ("07", "09"), "Q4": ("10", "12")}
    headers = ["Quarter", "Deductible Amount", "Transaction Count"]
    rows = []
    for q_name, (start_m, end_m) in quarters.items():
        q_txns = [t for t in tax_txns if start_m <= t.get("date", "")[5:7] <= end_m]
        q_total = sum(float(t.get("amount", 0)) for t in q_txns)
        rows.append([q_name, f"${q_total:,.2f}", str(len(q_txns))])
    pdf.add_table(headers, rows, [40, 60, 50])

    return pdf.get_bytes()


def generate_net_worth_statement(user_name: str, settings: dict, data: dict) -> bytes:
    """Generate a Net Worth Statement PDF report."""
    pdf = ReportPDF("Net Worth Statement", user_name)
    pdf.add_title_page(datetime.now().strftime("%B %d, %Y"))

    pdf.add_page()
    pdf.add_section_header("Assets & Liabilities")

    holdings = data.get("holdings", [])
    goals = data.get("goals", [])
    liabilities = data.get("liabilities", [])
    cash = float(settings.get("cash_balance", 0))

    portfolio_val = sum(h.get("purchase_price", 0) * h.get("quantity", 0) for h in holdings)
    goals_saved = sum(g.get("current", 0) for g in goals)
    total_assets = portfolio_val + goals_saved + cash
    total_liabilities = sum(float(l.get("balance", 0)) for l in liabilities)
    net_worth = total_assets - total_liabilities

    pdf.add_summary_box({
        "Total Assets": f"${total_assets:,.2f}",
        "Portfolio Value": f"${portfolio_val:,.2f}",
        "Savings Goals": f"${goals_saved:,.2f}",
        "Cash": f"${cash:,.2f}",
        "Total Liabilities": f"${total_liabilities:,.2f}",
        "Net Worth": f"${net_worth:,.2f}",
    })

    return pdf.get_bytes()


def generate_cash_flow(user_name: str, settings: dict, data: dict) -> bytes:
    """Generate a Cash Flow Analysis PDF report."""
    pdf = ReportPDF("Cash Flow Analysis", user_name)
    now = datetime.now()
    pdf.add_title_page(f"Last 6 Months ending {now.strftime('%B %Y')}")

    pdf.add_page()
    pdf.add_section_header("Monthly Cash Flow")

    transactions = data.get("transactions", [])

    # Monthly breakdown for last 6 months
    headers = ["Month", "Expenses", "Transaction Count"]
    rows = []
    for i in range(5, -1, -1):
        m = now.month - i
        y = now.year
        if m <= 0:
            m += 12
            y -= 1
        month_key = f"{y}-{m:02d}"
        month_txns = [t for t in transactions if t.get("date", "")[:7] == month_key]
        total = sum(float(t.get("amount", 0)) for t in month_txns)
        month_label = datetime(y, m, 1).strftime("%b %Y")
        rows.append([month_label, f"${total:,.2f}", str(len(month_txns))])

    pdf.add_table(headers, rows, [50, 50, 50])

    return pdf.get_bytes()


# Template registry
REPORT_TEMPLATES = {
    "Monthly Summary": generate_monthly_summary,
    "Year-in-Review": generate_year_in_review,
    "Tax Summary": generate_tax_summary,
    "Net Worth Statement": generate_net_worth_statement,
    "Cash Flow Analysis": generate_cash_flow,
}
